package gerenciamento.vo;
// Generated 25/10/2019 16:53:41 by Hibernate Tools 4.3.1



/**
 * Convidados generated by hbm2java
 */
public class Convidados  implements java.io.Serializable {


     private Integer idConvidado;
     private Evento evento;
     private String nome;
     private String cpf;
     private String levantamento;

    public Convidados() {
    }

	
    public Convidados(Evento evento) {
        this.evento = evento;
    }
    public Convidados(Evento evento, String nome, String cpf, String levantamento) {
       this.evento = evento;
       this.nome = nome;
       this.cpf = cpf;
       this.levantamento = levantamento;
    }
   
    public Integer getIdConvidado() {
        return this.idConvidado;
    }
    
    public void setIdConvidado(Integer idConvidado) {
        this.idConvidado = idConvidado;
    }
    public Evento getEvento() {
        return this.evento;
    }
    
    public void setEvento(Evento evento) {
        this.evento = evento;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getLevantamento() {
        return this.levantamento;
    }
    
    public void setLevantamento(String levantamento) {
        this.levantamento = levantamento;
    }




}


